# Github workflow runner instructions using customized actions
name: Code Coverage [CodeCov]

on: [ push ]

jobs:
  codecov:
    runs-on: ubuntu-20.04
    name: CodeCov
    steps:
      ##########   CHECK OUT REPO AND DOWNLOAD PACKAGES AND RUN COVERAGE & CODECOV #######
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry and python packages
        run: |
          pip install pyfiglet
          pip install -r requirements.txt
          pyfiglet Multi-Arch Build with GitHub Actions
      - name: Run Coverage
        run: coverage run simple_loop.py
      - name: Run CodeCov
        run: codecov --token=${{ secrets.codecov_token }}
