name: Deploy Pages

on:
  push:
    branches:
      - develop

jobs:
  documents:
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.11' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          python -m pip install -r requirements.txt

      - name: Set up Git
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ secrets.GH_EMAIL }}"
          git remote add gh-token "https://${{ secrets.PAT }}@github.com/ibrahimroshdy/continuous_integration.git"
          git fetch gh-token
          git checkout develop  # Ensure you are on the 'develop' branch
          git pull origin develop

      - name: Deploy documents
        run: python -m mkdocs gh-deploy -v --clean --remote-name gh-token
